### ISSUE TITLE
Doesn't work with python ver 3.10.5

### ISSUE THREAD

**Issue by Hatfa** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#10]
HA OS has been updated to core-2022.7.5 including an update to python 3.10.5. this is now causing issues with HA. My use case is the PCA 9685 which this had. Would be nice to have an alternative.

**Comment by RedMeKool** [comment]
Hi, with the latest switch to gpiozero (from release 2022.7.0 ) the support for the PCA9685 driver has been removed. Not sure if can be easily added for gpiozero as well.
