### ISSUE TITLE
2022.8.4  / HACS 1.26 no integration found

### ISSUE THREAD

**Issue by Rad3d21** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#12]
I'm not finding the integration via HACS 1.25 or 1.26. Is the version not compatible ?
The frequency is stated as default 100. Is this not the duty cycle ? So 100 = 100% on, 50 = 50% dimmed and 0 = off ?

**Comment by RedMeKool** [comment]
I bumped the version to 2022.8.5
See if you can find it on HACS now (assuming you are on 2022.8.5 already)..
I use the brightness (not the frequency) for control

**Comment by Rad3d21** [comment]
I was not but now I have upgraded to 2022.8.5. When adding via HACS I still cannot find this when using + Explore and download repositories. When using gpio or pwm in the search field it is only giving me 2 options but not this one. I guess I will have to go the manual way.

**Comment by RedMeKool** [comment]
Have you tried adding it as a custom repository (3 dots on top right)? Then adding the url of the repository

**Comment by Rad3d21** [comment]
Ok. that works. I didn't find the light so I also installed addon pigpio like mentioned. Restarted home-assistant. However starting that pigpio gives me the error https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/  :-(
