### ISSUE TITLE
Host is an invalid option

### ISSUE THREAD

**Issue by sm7xvd** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#13]
Getting the error 
`Invalid config for [light.rpi_gpio_pwm]: [host] is an invalid option for [light.rpi_gpio_pwm]. Check: light.rpi_gpio_pwm->host. (See ?, line ?). `

My conf is: 
`
light:
  - platform: rpi_gpio_pwm
    host: 172.17.32.107
    leds:
      - name: Lightstrip Cupboard
        pin: 18 
`

Pretty much from the example. I noted that CONF_HOST = was missing from light.py, so i tried adding it but to no avail. Any assistance with this please?

**Comment by RedMeKool** [comment]
The (optional) host parameter should go under led, not above.
Like this:

platform: rpi_gpio_pwm
leds:
-  name: Lightstrip Cupboard
    pin: 18
    host: 172.17.32.107
