### ISSUE TITLE
deprecated supported features (use of PwmSimpleLed)

### ISSUE THREAD

**Issue by mni82** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#29]
### System Health details

WARNING (MainThread) [homeassistant.components.light] Entity light.rpi_cooling_fan_rpi_gpio_pwm (<class 'custom_components.rpi_gpio_pwm.light.PwmSimpleLed'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.TRANSITION|1: 33> and color modes, please report it to the author of the 'rpi_gpio_pwm' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

### Checklist

- [ ] I have enabled debug logging for my installation.
- [ ] I have filled out the issue template to the best of my ability.
- [ ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [ ] This issue is not a duplicate issue of currently [previous issues](https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

WARNING (MainThread) [homeassistant.components.light] Entity light.rpi_cooling_fan_rpi_gpio_pwm (<class 'custom_components.rpi_gpio_pwm.light.PwmSimpleLed'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.TRANSITION|1: 33> and color modes, please report it to the author of the 'rpi_gpio_pwm' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

### Reproduction steps

1. Warning is shown in startup

### Debug logs

```text
See log after startup
```

**Comment by nielsnl68** [comment]
I have the same issue as above.

**Comment by RedMeKool** [comment]
Fixed by @erdnaxela02
