### ISSUE TITLE
On HA 2022.6.2 the configuration validation freezes

### ISSUE THREAD

**Issue by Dejv311** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#4]
If the HA-Raspberry-pi-GPIO-PWM (installed with HACS) is set up in the configuration.yaml the configuration validation is not able to finish and the system thus cannot restart.

Steps I tried:
reinstallation
manual installation
previous version (does not work no more)

**Comment by RedMeKool** [comment]
If you comment out any lights you defined temporarily, the system can restart. After updating you can remove the commenting again

**Comment by Dejv311** [comment]
The problem was in HACS GPIO integration. By the look of things the HACS installation has not finished succesfully before the update to 2022.6, but the depreciated internal integration was  enough to keep it alive anyways. After the update it silently stopped working, which also caused GPIO PWM to stop working.
