### ISSUE TITLE
Issue with core-2022.6.5 ?

### ISSUE THREAD

**Issue by leperroy** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#5]
Hello,

I'm on home assistant core-2022.6.5. When I try to validate my configuration I have : Platform error light.rpi_gpio_pwm - Integration 'rpi_gpio_pwm' not found.

In the configuration.yaml file :

light:
  - platform: rpi_gpio_pwm
    leds:
      - name: RPI Cooling Fan
        driver: gpio
        pins: [12]
        type: simple

I did manual installation, because not available in HACS

May thanks in advance for help

Guillaume

**Comment by RedMeKool** [comment]
Try to comment out the Led in your configuration and then reboot. See if you can update the module through HACS then.

**Comment by leperroy** [comment]
Hi

I did not install correctly the custom component. It pass the validation.

Nevertheless I have now in the log :

022-06-13 13:14:17 ERROR (MainThread) [homeassistant.components.light] Error while setting up rpi_gpio_pwm platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ha-rpi_gpio_pwm/light.py", line 97, in setup_platform
driver = GpioDriver(pins, **opt_args)
File "/usr/local/lib/python3.9/site-packages/pwmled/driver/gpio.py", line 25, in __init__
raise ConnectionError('Could not connect to the pigpio daemon')
ConnectionError: Could not connect to the pigpio daemon

I have installed the https://github.com/thecode/ha-rpi_gpio, and i can switch on/off.

**Comment by RedMeKool** [comment]
You are missing the pigpio daemon. You need to install this first: https://github.com/Poeschl/Hassio-Addons/tree/master/pigpio

**Comment by leperroy** [comment]
Ah. Thanks for the help. It works. Have a great day.
