### ISSUE TITLE
Failed to call service fan/turn_on. invalid state "10000" for pin GPIO14

### ISSUE THREAD

**Issue by si458** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#63]
## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4575
Installed Version | 1.34.0
Stage | running
Available Repositories | 1395
Downloaded Repositories | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 57.3 GB
disk_used | 24.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.17.0), Mosquitto broker (6.4.1), WireGuard (0.10.2), Advanced SSH & Web Terminal (18.0.0), File editor (5.8.0), ESPHome (2024.5.4), Log Viewer (0.17.0), Zigbee2MQTT (1.38.0-1), Whisper (2.1.0), Piper (1.5.0), Portainer (2.20.1), HassOS I2C Configurator (0.14), I2C OLED Display (1.0.5), pigpio (1.5.2), Epic Games Free (debian-2024-04-28), go2rtc (1.9.2), Speedtest (1.6.2), MQTT Explorer (browser-1.0.3), Neolink-latest (0.0.1), Network UPS Tools (0.13.0), Samba share (12.3.1), MeshCentral (1.1.22)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 8
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 May 2024 at 20:24
-- | --
current_recorder_run | 2 June 2024 at 22:57
estimated_db_size | 653.79 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

after upgrade to v2024.5.5, the control of my rpi fan no longer works
i keep getting an error saying `Failed to call service fan/turn_on. invalid state "10000" for pin GPIO14`

### Reproduction steps

1. install v2024.3.3
2. setup in json
3. restart ha
4. control fan, then stop fan
5. upgrade to v2024.5.5
6. restart ha
7. try turning on fan

### Debug logs

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gpiozero/pins/pigpio.py", line 245, in _set_state
    if value != self.factory.connection.get_PWM_dutycycle(self.number):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pigpio.py", line 1511, in get_PWM_dutycycle
    return _u2i(_pigpio_command(self.sl, _PI_CMD_GDC, user_gpio, 0))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pigpio.py", line 1011, in _u2i
    raise error(error_text(v))
pigpio.error: 'GPIO is not in use for PWM'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 328, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 337, in async_turn_on
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rpi_gpio_pwm/fan.py", line 177, in turn_on
    self._fan.value = self._percentage / 100
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gpiozero/devices.py", line 132, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gpiozero/output_devices.py", line 448, in value
    self._write(value)
  File "/usr/local/lib/python3.12/site-packages/gpiozero/output_devices.py", line 435, in _write
    super(PWMOutputDevice, self)._write(value)
  File "/usr/local/lib/python3.12/site-packages/gpiozero/output_devices.py", line 96, in _write
    self.pin.state = self._value_to_state(value)
    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gpiozero/pins/__init__.py", line 285, in 
    lambda self, value: self._set_state(value),
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gpiozero/pins/pigpio.py", line 248, in _set_state
    raise PinInvalidState('invalid state "%s" for pin %r' % (value, self))
gpiozero.exc.PinInvalidState: invalid state "5000" for pin GPIO14
```

**Comment by RedMeKool** [comment]
@erdnaxela02 This is the same issue

**Comment by mike4001** [comment]
Same here.

Also changing the fan speed is not possible

Changing to e.g. 84% says 

Fehler beim Aufrufen des Diensts fan/set_percentage. invalid state "8400" for pin GPI0

EDIT: Problem seems only to be valid if the pin is set up via UI. If I set it up in configuration.yaml the integration still works.

**Comment by RedMeKool** [comment]
Yes, I see the same behavior.  Reverting to config through yaml seems to be the workaround for now. 

I hope @erdnaxela02 has time to look at it cause setting it trough UI is a nice step forwards 😄

**Comment by casse-boubou** [comment]
Hello !
I have a good new!
After many, many, many tries, I FINALLY found what appears to be the root of the problem!
I explored a lot of avenues which turned out not to be the right ones. Many things surprised me since everything seemed ok to me.
But it's finding! I just have to find a way to make this clean. Hope to send you an update tomorrow :D

**Comment by RedMeKool** [comment]
That would be awesome!  I’ll check it as soon as you posted the push.

**Comment by RedMeKool** [comment]
Fixed in latest release
