### ISSUE TITLE
Raspberry pi 5 fan?

### ISSUE THREAD

**Issue by mennovanhout** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#66]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I can't get it working with the raspberry pi 5 fan.

### Describe the solution you'd like

It would be nice if we can add support for this

### Describe alternatives you've considered

I tried using it as pin 12 but it didn't really work

### Additional context

I have no clue if this connection is seen as a pwm pin or not.,

**Comment by casse-boubou** [comment]
This is not due to the custom component but directly to pigpio



    Pigpio is currently not supported on the PI 5. Until this happens officially, the addon will not work.

This is discussed here: https://github.com/joan2937/pigpio/issues/589

_Originally posted by @Poeschl in https://github.com/Poeschl/Hassio-Addons/issues/468#issuecomment-1987179039_

**Comment by RedMeKool** [comment]
Closing untill fixed officially
