### ISSUE TITLE
FanEntityFeature.TURN_OFF

### ISSUE THREAD

**Issue by mike4001** [RedMeKool/HA-Raspberry-pi-GPIO-PWM#86]
## System Information

version | core-2024.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4966
Installed Version | 1.34.0
Stage | running
Available Repositories | 1384
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 439.4 GB
disk_used | 22.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.3.2), Advanced SSH & Web Terminal (18.0.0), File editor (5.8.0), Samba Backup (5.2.0), Mosquitto broker (6.4.1), AppDaemon (0.16.6), Signal Messenger (0.88.0), MQTT Explorer (browser-1.0.1), ESPHome (2024.7.3), pigpio (1.5.2), Firefox (1.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 2
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15. Juli 2024 um 16:58
-- | --
current_recorder_run | 13. August 2024 um 09:06
estimated_db_size | 4569.16 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Logger: homeassistant.components.fan
Quelle: components/fan/__init__.py:295
Integration: Lüfter ([Dokumentation](https://www.home-assistant.io/integrations/fan), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
Erstmals aufgetreten: 09:06:24 (2 Vorkommnisse)
Zuletzt protokolliert: 09:06:24

Entity None (<class 'custom_components.rpi_gpio_pwm.fan.PwmSimpleFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/issues
Entity None (<class 'custom_components.rpi_gpio_pwm.fan.PwmSimpleFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/issues

### Reproduction steps

Just the log message which says to report the issue here :-)

### Debug logs

```text
Just the log message which says to report the issue here :-)
```

**Comment by casse-boubou** [comment]
Fix in PR https://github.com/RedMeKool/HA-Raspberry-pi-GPIO-PWM/pull/84
Waiting for RedMeKool to merge

**Comment by svh1985** [comment]
@RedMeKool Can you please check and merge the PR? My RPi is running hot without its fan 🥵. Thanks 🙏

**Comment by RedMeKool** [comment]
I just merged it, thanks @casse-boubou
